### PR TITLE
[SYSML-282] RowIndexMax and RowIndexMin operation on outer

### PR DESCRIPTION
**Pull request by asurve**
- Implemented RowIndexMax and RowIndexMin, on outer with <, <=, >, >=, == and != operator.
- Addressed all review changes from Pull Request # 39

### CODE REVIEW

**Comment by mboehm7** [comment]
Thanks Arvind for the generalization wrt to rowIndexMin. There are just a couple of final cleanups required:

1) Memory requirements: Could you please double check the rewrite memory constraints. For example, the factor of 2 for the mr rewrite is too low - you need at least a factor of 3 (the dcinput, the sorted values, and the prepared indexes).  Also, why is the direction RowCol missing in this constraint? What is with the other aggregations that do not require the prepared indices but the sorted values?
2) Lean library interfaces: Please, move the specific calls to prepareRowIndicesMax/Min from UaggouterChainInstruction and UaggouterChainSPInstruction into a generic prepareRowIndices inside the LibMatrixOuterAgg. 
3) Comments: There seems to be "tabs vs spaces" issue in the comments w/ examples. I really like the examples, but alignment is important here - please consistently use tabs or spaces. Thanks.

**Comment by mboehm7** [comment]
ok thanks Arvind, just one thing left: for AggOp.SUM, we need to take Direction.RowCol into account as well (line 511).

**Comment by asurve** [comment]
thanks Matthias, its done.

**Comment by mboehm7** [comment]
LGTM

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
