### PR TITLE
[SYSML-347] Invocation Tabs on Algorithms Reference

### PR DESCRIPTION
**Pull request by deroneriksson**
Added Hadoop and Spark tabs showing SystemML invocations to Algorithms Reference. Updated main.js for handling tabs. Updated DML and PyDML Programming Guide with respect to tab handling. Highlighted reference keys in Algorithms Bibliography. Fixed links in Quick Start Guide.

### CODE REVIEW

**Comment by lresende** [comment]
LGTM

**Comment by lresende** [comment]
PR Merged

**Comment by shirisht** [comment]
Deron, could you remove "--conf spark.akka.frameSize=128" from Spark invocation, since it is same as the default value. Since, this JIRA is closed already .. you can take care of it as part of other documentation-related JIRAs that you are working on.

**Comment by mboehm7** [comment]
well 128MB its the default in Spark 1.5 while versions <1.5 had 10MB which often shows up as a problem - please leave this for now.

**Pull request closed without merging**
