### PR TITLE
[SYSML-292] PyDML bool print with correct case

### PR DESCRIPTION
**Pull request by deroneriksson**
Previously, if a PyDML bool was printed, it would appear as TRUE/FALSE rather than True/False, even though bool values need to be specified as True/False in PyDML. An awareness of the script type needs to be passed down to the level where it is needed in order to generate case-correct output. Boolean case conversions were added to ScalarBuiltinCPInstruction, ArithmeticBinaryCPInstruction, and RewriteConstantFolding via a PyDMLUtils.convertBooleanStringToPyDMLBooleanString() method. Additional code modifications were made to pass the ScriptType awareness where necessary so that it could be placed in an ExecutionContext for access. The ScriptType is set on the ExecutionContext object via a setter method in RewriteConstantFolding so that it has the flexibility to correctly handle setting the script type in cases such as if a PyDML test runs after a DML test.

### CODE REVIEW

**Comment by deroneriksson** [comment]
The following PyDML statements print out with the correct case:
```python
print(True)
print(False)
b = True
print(b)
print(!b)
print(1>2)
print(2>1)
print(1==1)
print(1==2)
print('a' == 'a')
print('result:' + ('a' == 'a'))
print(True + ' ok')
print(True + ' : ' + False)
print('testing1:' + (1.0 > 2.0))
print('testing2:' + (1.0 == 2.0))
a = True
b = False
print('(a|b):' + (a|b))
print('(a&b):' + (a&b))
print('!(a|b):' + !(a|b))
print('!(a&b):' + !(a&b))
print((a|b))
print((a&b))
print(!(a|b))
print(!(a&b))
for (i in 1:3):
	print(i<2)
	print('i<2:' + (i<2))
```

**Comment by mboehm7** [comment]
sorry but for now I have to reject this PR. We decided that the python/dml parsers map to the same compiler/runtime w/o exceptions. Examples where this creates inconsistencies are 1-based indexing and this instance of printing boolean scalars. A proper handling would require various extensions of the compiler / runtime including error handling (e.g., for this print you would also need to modify ScalarBuiltinCPInstruction and ScalarScalarBuiltinCPInstruction - otherwise you capture only constants). The advantage of a common compiler/runtime is consistency and simplicity. For example, 0-based indexing would create inconsistencies with the input data formats textcell/matrix market which specify row/col-indices in a 1-based manner. The disadvantage is certainly ramp-up time for python developers - for now we accept this, unless it turns out that the majority of our users are indeed python developers.

**Comment by mboehm7** [comment]
just as a potential compromise for this specific issue of printing scalars: we could capture the script type at dml script level, provide a static util method that prints according to the script type, and the actual prints just call this method - this would allow us to keep the compiler/runtime clean and still resolve this inconsistency.

**Comment by deroneriksson** [comment]
Thank you for looking at this @mboehm7. I definitely see lots of value to the idea of a consistent compiler/runtime. As for the idea of having the prints call a static print utility method, I think that could potentially be a very clean solution if that can be accomplished with regards to issues like the constant folding (for things like `print('a' == 'a'); print('result:' + ('a' == 'a'))`). It could have added benefits too. For instance, if all the output goes through a common point, potential functionality such as filtering the output or writing the output to a file could be performed easily.

I think it would be very nice though to have the bool output from PyDML match the bool keywords 'True' and 'False' in the Pydml.g4 grammar though, since I experience a cognitive dissonance when I write PyDML with bool True/False but the corresponding output values are TRUE/FALSE, which aren't accepted in PyDML.

**Comment by mboehm7** [comment]
sure - I understand that this issue is really ugly because it does not just diverge from python but is inconsistent in itself. @deroneriksson Could you then please try to create such a fix that only changes DMLScript, UtilFunctions and the cp instructions that actual print to stdout (e.g., script type in dmlscript, print functions in utilfunctions and their usage in the scalar builtin instructions). There should be no additional changes required because any literal construction and usage would be independent of the actual externally visible representation. Btw, scenarios like this are a reason why constant folding generates and executes runtime instructions for consistency.

**Comment by shirisht** [comment]
Apart from these changes that handle the output/prints, we should also handle the inputs appropriately. Two things here -- the constants specified in the given DML script as well as the command line parameters provided by the user at the time of script execution. In both these cases, the input constants True/False must be properly mapped to boolean types (in the parser layer).

**Comment by shirisht** [comment]
Sorry, the input side of things is already been handled.

**Comment by shirisht** [comment]
Scalars can also be read and written to HDFS files using read() and write(). We need to handle that path as well. 
Currently, there seems to be an inconsistency -- we always read/write booleans as true/false (as in Java constants). This behavior is OK if the written files are used only by SystemML, but they can not be processed by either R or Python. Therefore, the "script type" related changes have to be reflected also in readBooleanFromHDFSFile() and writeBooleanFromHDFSFile() functions from MapReduceTool.

**Comment by deroneriksson** [comment]
@mboehm7 Looking at the code, I don't think I'm able to create an unobtrusive solution given my current level of understanding of SystemML. For example, the `String rval = dop.fn.execute(val1, val2)` in `ScalarScalarArithmeticCPInstruction` (if one of the inputs is a String and the other is a boolean) results in a String representing a concatenated String and boolean, and this resulting String can be output in `ScalarBuiltinCPInstruction`. The `ScalarBuiltinCPInstruction` sees the result as a String rather than as a String and a boolean, so the knowledge of the boolean has been lost, and doing the case conversion on the String rather than on a boolean isn't a clean solution.

As an example, if I have:
```r
print('result:' + ('a' == 'a'))
```
and in `ScalarScalarArithmeticCPInstruction` I have:
```java
String rval = dop.fn.execute(val1, val2);
rval = "<2>" + rval + "</2>";
```
and in `ScalarBuiltinCPInstruction` I have:
```java
System.out.println("<1>"+outString+"</1>");
```
I obtain:
`<1><2>result:TRUE</2></1>`
which shows the boolean is being treated as a String by the time it is output in `ScalarBuiltinCPInstruction`.

So it's probably a good idea for me to work on other issues for the time being. When time permits, perhaps someone with a deeper knowledge of SystemML can come up with a clean solution?

**Comment by mboehm7** [comment]
ok thanks for the input - I'll have a look in the next couple of weeks.

**Comment by deroneriksson** [comment]
I will close this PR as it is not ideal, as discussed.

**Pull request closed without merging**
