### PR TITLE
[SYSML-328] Markdown for additional algorithms

### PR DESCRIPTION
**Pull request by deroneriksson**
Created markdown for ALS, Cox, DecisionTrees, KaplanMeier, RandomForest, StepGLM, and StepLinRegDS. Additionally, minor updates to existing algorithm markdown.

### CODE REVIEW

**Comment by shirisht** [comment]
Thanks for including additional algorithms. Few comments after taking a quick look.

* A general comment is that all the example invocations (hadoop jar SystemML.jar ..) are for MR backend, and we don't have any examples for Spark backend.
* Under matrix factorization, could you please cleanup "Returns" section under PCA? The current text has some LaTeX symbols.
* In the Usage, could you please highlight arguments by placing them within brackets? For example, `<file>` or `[file]` (`[]` indicates optional).
* LaTeX sumbols are present in "Details" and "Returns" sections of ALS as well. Please fix them across all algorithms.
* The back reference to algorithms-reference.html leads to page not found error. Also, the references to bibliography.

**Comment by frreiss** [comment]
I would vote for having three tabs -- "Hadoop", "Spark", and "MLContext" -- for each of the example invocations, the same way that the Spark docs have Scala/Java/Python. The first two would be command-line arguments, while the third would be Scala code.

**Comment by niketanpansare** [comment]
I second Fred's suggestion. @deroneriksson we can discuss spark invocation offline :)

**Comment by shirisht** [comment]
On a related note: can you please also update the quick start guide to include Hadoop and Spark invocations, and not focus on standalone mode (which we do not advocate strongly). This can probably be taken care in a different JIRA, if you prefer.

**Comment by deroneriksson** [comment]
@frreiss @niketanpansare I also like the three tab suggestion. I will probably split that to another JIRA since this one is quite large already and it will require some Javascript updates to work with the tabs elsewhere in the generated docs.

@shirisht Quick start guide updates would go well in another JIRA. @ckadner currently is mainly responsible for the quick start guide. I will file a JIRA and find out whether he or I should make the updates.

Also updated documentation to be version 0.8.0.

Still adding the highlighted arguments (<...> and [...]) to the Usages.

**Comment by shirisht** [comment]
Great, Thank you for taking care of all these changes.

**Comment by deroneriksson** [comment]
Added highlighted arguments to usages. I believe all the current issues have been addressed regarding the Algorithms Reference except the tabbed invocations (Hadoop, Spark, and MLContext), which will be addressed in a separate JIRA.

**Comment by shirisht** [comment]
LGTM overall.
Only additional comment (which you may fix as part of other JIRA): In bibliography, the citation keys (e.g., AcockStavig1979) must be highlighted in bold or be placed in brackets.

**Comment by deroneriksson** [comment]
Thank you @shirisht. I will bold the citation keys in a separate PR.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
