### PR TITLE
UggOuterChain AllSum, Sort w/ index broadcasting and RemoveEmpty with offset broadcasting

### PR DESCRIPTION
**Pull request by asurve**
All Sums (Reduce all) operation support for <, <=, >, >=, == and !=
operators in Unarry Agrrrgator Outer Chain.

### CODE REVIEW

**Comment by mboehm7** [comment]
looks good to me.

**Comment by mboehm7** [comment]
the two additional commits look good as well except for the changes in RDDSortUtils - there is some cleanup required:
1) directly pass the spark execution context to sortDataByValMemSort
2) avoid temp variable declarations w/o assignments
3) avoid modification of external arguments (r_op)
4) avoid unnecessary data copies (in order to flip the indexes, please create an empty output matrix and append to it); however, make sure to stick to the memory requirements of 2x the index vector
5) fix the broken comments
6) remove unused functions like ExtractTargetIndex

**Comment by asurve** [comment]
Addressed review comments.

**Comment by mboehm7** [comment]
looks good to me - @lresende please merge in

**Comment by lresende** [comment]
@asurve could you please double check if your e-mail is correct on these commits.

**Comment by asurve** [comment]
yes, e-mail id is correct one, please merge my changes. thanks

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
