### PR TITLE
[SYSML-132] Refactor test classes/scripts for mtd, remove legacy code, PyDML spaces

### PR DESCRIPTION
**Pull request by deroneriksson**

### CODE REVIEW

**Comment by mboehm7** [comment]
in general it's fine; @lresende it can be merge; However, @deroneriksson could you please in the future cleanup the commented source code (e.g., test parameters for debugging, old input arguments, etc), unnecessary prints to stdout, as well as unnecessary indirections (e.g., exception_expected);  thanks.

**Comment by deroneriksson** [comment]
Hello @mboehm7. When working on a test with a Parameters-annotated class, typically I run one set of test parameters until the work is done, at which time I run all the sets of test parameters. I left the commented-out single sets of test parameters as a convenience. However, this does lead to less-clean code, so I will delete these. I will also try to remove other unnecessary content from the source code.

With regards to the EXCEPTION_NOT_EXPECTED parameters to the runTest() invocations, I created the EXCEPTION_EXPECTED and EXCEPTION_NOT_EXPECTED constants in AutomatedTestBase to increase readability. The use of the constants makes it visually clear whether an exception is expected or not expected when runTest() is called. Otherwise, to understand the purpose of the second parameter of this runTest() method, a developer needs to inspect the method whereas the use of the constants make it immediately clear what that parameter is doing. So if possible I would like to keep this addition.

**Comment by deroneriksson** [comment]
@mboehm7 Also, I believe all of the tests in the integration.applications.* package have their input arguments cleaned up. It turned out that when I changed integration.applications.GNMFTest to utilize writeInputMatrixWithMTD() and adjusted the GNMF dml/pydml scripts accordingly, this broke the integration.functions.mlcontext.GNMFTest class. As a result of this unexpected dependency, I only refactored integration.functions.mlcontext.GNMFTest insofar as was minimally needed to make it work with the new GNMF.dml script. I will go ahead and refactor this class to match the rest of the style in the integration.applications.* package.

**Comment by deroneriksson** [comment]
Pushed requested updates to branch.

**Comment by mboehm7** [comment]
LGTM - thanks

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
