### PR TITLE
[SYSML-132] PyDML for ArimaTest, LinearLogRegTest, and MultiClassSVMTest

### PR DESCRIPTION
**Pull request by deroneriksson**
PyDML scripts added for ArimaTest, LinearLogRegTest, and MultiClassSVMTest, and Java test classes modified and added accordingly.

### CODE REVIEW

**Comment by mboehm7** [comment]
Deron, as mentioned before, could you please cleanup the handling of input dimensions while modifying these tests? For example, parameters like
    proArgs.add(Integer.toString(rows));
    proArgs.add(Integer.toString(cols));
should be removed for application tests because by default we rely on meta data files. You can simply write the inputs with
    writeInputMatrixWithMTD("X", X, true, mc);
and change the script to
    X = read($1);
(where meta data is read from {$1}.mtd). Thanks.

**Comment by deroneriksson** [comment]
Matthias, thank you for the clarification. I will do so.

**Comment by deroneriksson** [comment]
Cleaned up handling of input dimensions for LinearLogRegTest. Additionally made some minor updates to simplify some boilerplate code in test cases.

**Comment by mboehm7** [comment]
looks good to me; thanks @deroneriksson; @lresende please merge.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
