### PR TITLE
[SYSML-327] Add additional algorithm tex files to Algorithms Reference

### PR DESCRIPTION
**Pull request by deroneriksson**
Added following tex files to docs/Algorithms Reference:
ALS.tex, Cox.tex, KaplanMeier.tex, RandomForest.tex, StepGLM.tex, StepLinRegDS.tex
Updated:
SystemML_Algorithms_Reference.bib, SystemML_Algorithms_Reference.pdf, and SystemML_Algorithms_Reference.tex

### CODE REVIEW

**Comment by shirisht** [comment]
Deron, Thanks for getting the docs up-to-date. Could you please update the date in the generated PDF? It still shows Aug 16th? Otherwise, it looks good.

**Comment by deroneriksson** [comment]
@shirisht Generated a new PDF. Additionally changed \r\n in new tex files to \n to match other tex files in repository. Also updated LinReg.tex, GLM.tex, and DecisionTrees.tex to contain latest updates from August.

**Comment by shirisht** [comment]
Thanks, Deron.

**Comment by shirisht** [comment]
LGTM

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
