### PR TITLE
[SYSML-364] Remove snapshot references in MLContext guide

### PR DESCRIPTION
**Pull request by deroneriksson**
Versioned snapshot jar references removed from MLContext Programming Guide and replaced with generic SystemML.jar file.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Added a link to binary releases from Quick Start Guide.

**Comment by shirisht** [comment]
Deron, 

Instead of simply adding a link to the binaries, can we add a new section "Download SystemML" or something of that sort after the first section "What is SystemML?". 
While you are at it, could you also add some text to explain *Standalone* mode -- what it contains and when it should be used? .. that it packs all the required Hadoop libraries, that it should be used in non-Hadoop environments, and that it forces the execution of all operations on a single node and hence, should be used only for quick prototyping and not for large data sets. 

Thanks.

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by deroneriksson** [comment]
Added Download SystemML section and added brief description of standalone mode to Standalone vs Distributed Execution Mode section.

**Comment by lresende** [comment]
LGTM

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
