### PR TITLE
[SYSML-313] Update unit test subset to demonstrate proposed refactoring

### PR DESCRIPTION
**Pull request by gweidner**
This PR contains changes to base test class plus updates to all unit tests of two sample packages (functions.binary.matrix_full_other and functions.binary.matrix_full_cellwise).  This set relocates the generated test data storage outside of the src tree for the selected packages without impacting unit tests from other packages to be updated.  The pom.xml will also be updated separately.  Additional rationale for the changes as part of reducing test harness runtime is described in document attached to SYSML-286.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by gweidner** [comment]
Noticed test failure in corresponding Jenkins build 12 but have not been able to reproduce same com.ibm.bi.dml.test.integration.applications.descriptivestats.UnivariateWeightedScaleSparseTest.testWeightedScale6 failure in my local environment.  Note issue reported in SYSML-315 was reproduced on my local test system:

Failed tests:
  WhileTest.testCleanUp:97 unable to remove temporary files: Directory C:\git\systemml\system-ml\temp924_544 is not empty
  ReblockRecompileTest>AutomatedTestBase.tearDown:1351 Detailed matrices characteristics:
!  DML<->R # stored values in DML: 20
!  DML<->R # stored values in R: 3
!  DML<->R identical values(z=0): 16
!  DML<->R wrong values(z=1.0E-10): 4
!  DML<->R min error: 0.0
!  DML<->R max error: 8.0


Tests run: 3912, Failures: 2, Errors: 0, Skipped: 2

[INFO]
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ system-ml ---
[INFO] Failsafe report directory: C:\git\systemml\system-ml\target\failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:10 h
[INFO] Finished at: 2015-09-23T02:10:44-07:00
[INFO] Final Memory: 68M/216M
[INFO] ------------------------------------------------------------------------

**Comment by akchinSTC** [comment]
The issue is intermittent, don't know the cause as of yet. I have requested a retest.

**Comment by mboehm7** [comment]
@shirisht please take a look

**Comment by gweidner** [comment]
I've added one commit for the pom.xml to run the updated individual unit tests from the two packages full_matrix_other and matrix_full_cellwise (instead of running their corresponding Suites).  Note on my system this reduced the overall time to complete 3980 tests by 20 minutes:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:37 h
[INFO] Finished at: 2015-09-27T00:37:28-07:00
[INFO] Final Memory: 62M/192M
vs
[INFO] Total time: 03:56 h
[INFO] Finished at: 2015-09-27T13:36:57-07:00
[INFO] Final Memory: 69M/207M

At a minimum, this approach should at least eliminate the Suites and reduce code.  Additional savings involving R-scripts is being investigated separately.

**Comment by shirisht** [comment]
Overall the code structure looks good, and the improvement in total runtime is impressive. Few minor points:
- Please rename SCRIPT_TARGET_DIR  to TEST_DATA_DIR, for clarity.
- Can we simplify the implementation of isTargetTestDirectory() to "return (path != null && path.contains(getClass().getSimpleName()))"?
- The check for null in Line 745 (testDirectory != null) is redundant since you check for null in isTargetTestDirectory().
- While initializing TARGET_IN and TARGET_OUT, appending TEST_CLASS_DIR is redundant since SCRIPT_TARGET_DIR already has the test name within it (set while loading the test configuration).

@akchinSTC Is there any update on WhileTest? What is the result of retest? That failure seems unrelated to this commit.

**Comment by gweidner** [comment]
Thank you Shirish for your time and thorough feedback.  I'm working on incorporating each of your recommendations and will add commits to this branch after retesting in my local environment.  Note I've been able to make additional time improvements related to SYSML-319 which layers on top of these changes.

**Comment by gweidner** [comment]
I've added commits to incorporate three of the code review items.  The last point regarding TARGET_IN and TARGET_OUT was left unchanged to keep in, out, expected subfolders at same level for a given test class.  This can be revisited as part of SYSML-319 where the 'expected' folder created under TEST_CLASS_DIR is being used across test names for a given test unit class.

**Comment by akchinSTC** [comment]
@shirisht I believe the problem was corrected after merging of PR #32

**Comment by gweidner** [comment]
Restored pre-existing check for null to fix regression in functions.terms.ScalarToMatrixInLoopTest.

**Comment by shirisht** [comment]
@gweidner  Thanks for the corrections.
LGTM  @lresende  please merge.

**Comment by lresende** [comment]
PR Merged

**Comment by gweidner** [comment]
SYSML-342 synchronized FullMatrixMultiplicationTest.java.

**Pull request closed without merging**
