### PR TITLE
[SYSML-282] CP implementation for UaggOuterChain supported functions

### PR DESCRIPTION
**Pull request by asurve**
All functions supported through LibMatrixOuterAgg are supported through CP platform as well.

### CODE REVIEW

**Comment by mboehm7** [comment]
thanks Arvind - good that you resolved the nnz meta data issue. Couple of additional comments:

1) Memory estimates default case: Please, be careful about intermediate memory estimates; currently, your change would affect the intermediate memory estimate of ALL unary aggregates, not just unary aggregates over outer operations.
2) Memory estimate uaggouterchain: Could you please double check the intermediate memory estimate for maxindex, minindex? Uaggouterchain does not require the corrections and hence should at most require 3x not 4x the vector size.
3) Matrix block operations: Could you please create a uaggouterchainOperations method in our core matrix block structure and move the code for output setup and library handling into this block operation? It would be nice if the instruction just handles inputs/outputs and calls the block operation because this will simplify future reuse.

**Comment by mboehm7** [comment]
this looks already pretty good - just two more comments:
1) Block operations: please don't use getMaxRow and getMaxColumn (ctable-specific attributes) but getNumRows and getNumColumns. In your case, the tests succeeded because your input is dense. 
2) Sparsity awareness: It is very reasonable to assume dense outputs; however, in specific cases (e.g., colsum) the output might qualify for a sparse representation. Please call examSparsity in your instruction after you unpinned (released) the inputs - this will cover any potential memory requirements for the representation change.
3) Comments: please, fix the grammar of "resulting matrix is mostly likely be dense".

**Comment by mboehm7** [comment]
LGTM; @lresende please merge.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
