### PR TITLE
[SYSML-365] Enable binary.matrix tests to run in parallel

### PR DESCRIPTION
**Pull request by gweidner**
This PR covers the 25 unit test classes for package functions.binary.matrix and contains symmetrical changes as were done/reviewed in PR #64.

Note the 2 extra commits for AutomatedBaseTest.class and ScalarMatrixUnaryBinaryTermTest.java/ScalarToMatrixInLoopTest.java are identical in content to PR 64 but were included only to ensure automated PR builder full unit test harness for this request passes (since PR 64 not yet in master).

### CODE REVIEW

**Comment by gweidner** [comment]
Rebased and reset branch such that only files for binary.matrix are included to resolve conflicts (i.e., Scalar tests and AutomatedBaseTest addressed in other PRs).  Test failures can be ignored.

**Comment by gweidner** [comment]
Note tests passed for PR #64 and contains updated AutomatedBaseTest.java which resolves test failures.

**Comment by gweidner** [comment]
PR #64 does not appear to be merged to master yet based on master branch commit history.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
