### PR TITLE
[SYSML-362] Enable unit tests in functions.unary.matrix to run in parallel

### PR DESCRIPTION
**Pull request by gweidner**
This set of commits update and enable the unit tests in package functions.unary.matrix to be run in parallel instead of using corresponding package suite class.  The changes follow similar pattern used in SYSML-313.
1) First commit covers the 28 test classes.
2) Second commit includes two classes from package functions.terms [SYSML-361].
3) Third commit updates the base test class as required for tests where 'newWay' flag for runTest is false.
4) Fourth commit updates the pom.xml file to run the individual unit tests instead of package suite class.

### CODE REVIEW

**Comment by frreiss** [comment]
LGTM overall.

I do see the lines 
		String TARGET_IN = TEST_DATA_DIR + TEST_CLASS_DIR + INPUT_DIR;
		String TARGET_OUT = TEST_DATA_DIR + TEST_CLASS_DIR + OUTPUT_DIR;
		String TARGET_EXPECTED = TEST_DATA_DIR + TEST_CLASS_DIR + EXPECTED_DIR;
repeated quite a bit, though. You might want to move the construction of those paths into the superclass.

**Comment by gweidner** [comment]
Thank you Fred for the great suggestion!  I made additional commit for 16 of the test classes which definitely made the code cleaner:
1) Removed TARGET_ variables and replaced with references to base class input/output/expected directory methods.
2) Moved/Merged loadTestConfiguration before accessing directory methods to ensure baseDirectory initialized.

**Comment by frreiss** [comment]
LGTM. Not sure what is up with Jenkins; the build looks clean to me.

**Comment by gweidner** [comment]
Thanks again for the review.  Note I've seen the same type failure (where 97 tests each not run in applications.dml and applications.pydml) in other PRs, e.g.,
https://github.com/SparkTC/systemml/pull/59 where Jenkins retest was successful.

I've run full harness on my laptop with the combined changes from both this PR and PR for [SYSML-351] (Enable tests in functions.append to run in parallel).  The total test harness time was observed under 3 hours for the first time on my local system (2 hr 51 min).  I need to re-run with optimizations turned off for comparison to determine current savings, although last Sunday I ran without any optimizations where the total time was closer to 3 1/2 hours (3 hr 26 min) for the 4065 tests.

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by shirisht** [comment]
Glenn, a couple of additional comments:

* Please fix formatting around lines that invoke new input() function ... a lot of lines have unnecessary white spaces.
* Remove unnecessary/old comment from EigenFactorizeTest.setUp()
* Can you combine individual tests (such as ACosTest, ASinTest, ATanTest, etc.) under functions.unary.matrix package into a single file -- this should include all the following builtins: abs, sin, cos, tan, asin, acos, atan, sqrt, log, exp, round, ceil, floor, inverse, cast_as_scalar. Feel free to create a new PR, if you wish.

**Comment by gweidner** [comment]
Thank you Shirish for the go-ahead to cleanup formatting.  For the initial commits I thought I had left white-space and line placement mostly as-is but have reformatted with most recent commit addressing 16 files.  Some statements were continued to next line if exceeded 100 chars.  If I didn't quite get the formatting or style (e.g., {} alignment), please let me know and I will correct.    I will open a separate PR for combining the other tests as I've made changes to other packages (e.g., aggregate) in effort to bring down time a little further.

**Comment by shirisht** [comment]
LGTM
@lresende Please Merge
@gweidner Please take care of combining Unary tests in a separate PR.

**Comment by shirisht** [comment]
BTW @gweidner, Regarding whitespaces and formatting: source code spanning multiple lines is totally fine but just make sure about appropriate spacing.

**Comment by gweidner** [comment]
Thank you - I've opened separate JIRA [SYSML-369] for combining the tests under different PR.

**Comment by shirisht** [comment]
LGTM
@gweidner .. please also make sure pom.xml is updated to reflect all parallel tests that you enabled through other JIRAs.

**Comment by lresende** [comment]
PR Merged

**Comment by gweidner** [comment]
PR #64 does not appear to be merged to master yet based on systemml master branch commit history which shows sysml-368 as latest commit November 3.

**Comment by lresende** [comment]
Sorry, I merged and didn't push, it should be in trunk now.

**Comment by gweidner** [comment]
Thank you Luciano - I see it in trunk and will rebase the other 2 PRs.

**Pull request closed without merging**
