### PR TITLE
FIX: Constant Folding expression parent input update

### PR DESCRIPTION
**Pull request by asurve**
In the ConstantFoldingExpression, evaluation of children input was not updated in parent input. This was causing some statements not to fold.

### CODE REVIEW

**Comment by mboehm7** [comment]
thanks Arvind - that's a great catch. I thought about it after our discussion and would recommend a slightly different approach. Your change would lead to redundant operator replacements for the common case of numeric constants (non conjunctive/disjunctive predicates), which currently do reverse replacement in order to keep eliminated common subexpressions. Also note that root node folding already worked for partial conjunctive/disjunctive predicates - the bug only occurs for inner nodes of partial predicates that can be folded. May I ask you to rewrite it in a way that does reverse replacement once for all the different cases if it is not already a root node. Finally, please use HopRewriteUtils.removeChildReferenceByPos and HopRewriteUtils.addChildReference(..., pos) in order to properly clean up the bidirectional references. Thanks.

**Comment by mboehm7** [comment]
LGTM; @lresende please merge.

**Comment by asurve** [comment]
Please hold on this merge, as one test case is failing. Investigating ...

**Comment by lresende** [comment]
Test this Jenkins

**Comment by mboehm7** [comment]
closed because this pr is replaced by #72

**Pull request closed without merging**
