### PR TITLE
[SYSML-366] Enable aggregate tests to run in parallel

### PR DESCRIPTION
**Pull request by gweidner**
This PR covers the 15 unit test classes for package functions.aggregate and contains symmetrical changes as was done/reviewed in PR https://github.com/SparkTC/systemml/pull/64.

Note the 2 extra commits for AutomatedBaseTest.class and the ScalarMatrixUnaryBinaryTermTest.java/ScalarToMatrixInLoopTest.java are identical in content to PR 64 but were included only to ensure automated PR builder full unit test harness for this request passes (since PR 64 not yet in master).

### CODE REVIEW

**Comment by gweidner** [comment]
Rebased and adjusted commits to resolve conflicts with files committed through other PRs.  Note test failures can be ignored.

**Comment by gweidner** [comment]
Note tests passed for PR #64 which contains updated AutomatedBaseTest.java which resolves test failures.

**Comment by gweidner** [comment]
PR #64 does not appear to be merged to master yet based on master branch commit history.

**Comment by gweidner** [comment]
I've rebased to include merged PR 64 so tests should all pass.

**Comment by gweidner** [comment]
I've rebased to include merged PR #64 so tests should all pass.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
