### PR TITLE
Run standalone from source

### PR DESCRIPTION
**Pull request by ckadner**
This PR adds two new run scripts to execute SystemML directly from the source project, eliminating the need to build and extract a standalone package.

These are the steps required to run SystemML after this change:
```
$ git clone https://github.com/SparkTC/systemml.git
$ mvn clean compile
$ ./bin/systemml XYZ.dml -nvargs ...
```
**A few usage notes:**
- if you run the script from the project root folder `./` or from the `./bin` folder, then the output files from running SystemML will be created inside the `./temp` folder to keep them separate from the SystemML source files managed by Git. The `./temp` folder and its contents will be ignored by Git

- the runtime behavior and logging behavior of SystemML can be customized by editing the files `./conf/SystemML-config.xml` and `./conf/log4j.properties`. Both files will be created from their corresponding `*.template` files during the first execution of the SystemML executable script (and will consequently be ignored by Git)

- when invoking the `./bin/systemml` or `.\bin\systemml.bat` with any of the prepackaged DML scripts you can omit the relative path to the DML script file (just the DML file name is sufficient). The following two commands are equivalent:
```
./bin/systemml ./system-ml/scripts/datagen/genLinearRegressionData.dml -nvargs numSamples=1000 numFeatures=50 maxFeatureValue=5 maxWeight=5 addNoise=FALSE b=0 sparsity=0.7 output=linRegData.csv format=csv perc=0.5

./bin/systemml genLinearRegressionData.dml -nvargs numSamples=1000 numFeatures=50 maxFeatureValue=5 maxWeight=5 addNoise=FALSE b=0 sparsity=0.7 output=linRegData.csv format=csv perc=0.5
```
**New files:**
```
bin/systemml.bat                              # run script Windows
bin/systemml                                  # run script Linux/Mac
conf/log4j.properties.template                # log4j configuration template
conf/SystemML-config.xml.template             # SystemML configuration template
system-ml/src/test/scripts/testRunScript.bat  # test suite for run script (Win)
system-ml/src/test/scripts/testRunScript.sh   # test suite for run script (Linux/Mac)
```

**Modified files:**
```
system-ml/dependency-reduced-pom.xml    # 
system-ml/pom.xml                       # copy hadoop binaries to target, incl. winutils
system-ml/src/assembly/standalone.xml   # change scripts folder structure the standalone jar
README.md                               # describe run scripts, modify examples
.gitignore                              # exclude ./temp/* and non-template files under ./conf
```

**Next steps:**
- enhance the run script to run in Hadoop and Spark
- modify the Quick Start Guide which still refers to building a standalone package

### CODE REVIEW

**Comment by ckadner** [comment]
@dusenberrymw, @deroneriksson, @niketanpansare 
Could you give this a spin and comment on this PR? Thanks a bunch!

**Comment by ckadner** [comment]
as Mike suggested, I removed the file extension `.sh` from `systemml.sh` (as Spark has it)

**Comment by niketanpansare** [comment]
Looks good to me.

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by ckadner** [comment]
Hi Alan,

can you fix this problem?  :-)


Error Message
unable to remove temporary files:
Directory /a/workspace/SystemML-PullRequestBuilder/system-ml/temp623_396 is
not empty

Stacktrace
java.lang.AssertionError: unable to remove temporary files:
Directory /a/workspace/SystemML-PullRequestBuilder/system-ml/temp623_396 is
not empty
		 at org.junit.Assert.fail(Assert.java:88)
		 at com.ibm.bi.dml.test.utils.TestUtils.removeTemporaryFiles
(TestUtils.java:1813)
		 at
com.ibm.bi.dml.test.integration.functions.blocks.WhileTest.testCleanUp
(WhileTest.java:97)



Best regards,
Christian Kadner

**Comment by dusenberrymw** [comment]
@ckadner This has been fixed in https://github.com/SparkTC/systemml/pull/32.  As soon as that one is merged, this error will go away.

**Comment by lresende** [comment]
Test this Jenkins

**Comment by dusenberrymw** [comment]
@ckadner @lresende Now that https://github.com/SparkTC/systemml/pull/32 has been merged, this will need to be debased on top of master before the tests will (reliably) pass.

**Comment by dusenberrymw** [comment]
LGTM.  Awesome work, Christian!  This is going to be great to have.

**Comment by ckadner** [comment]
I just opened [PR-42](https://github.com/SparkTC/systemml/pull/42) for easier merge into master. Thanks @lresende !

**Comment by lresende** [comment]
Closing this without merge, as @ckadner is creating a new and clean pr to make my life easier on the merge process. Thanks @ckadner

**Pull request closed without merging**
