### PR TITLE
[SYSML-282] Outer binary comparison implementation

### PR DESCRIPTION
**Pull request by asurve**
- Implemented changes for matrix outer operation for following operators
   <, <=, >, >=, == and !=

### CODE REVIEW

**Comment by mboehm7** [comment]
1) Correctness NNZ: Due to the custom array fill w/ 1s you need to explicitly maintain the number of non-zeros.
2) Correctness sparse data: The method isSorted is incorrect in case of sparse input data; please use DataConverter.convertToDoubleVector to make this independent of the sparse/dense representation.
3) Check for isSorted: We have already a check for isSorted in SortUtils but for int arrays. Please add a similar method for double values and just call this util function.
4) Dense output allocation: Please think about alternative preprocessing steps to figure out dense/sparse output allocation - in case of actually sparse output data, the dense allocation will unnecessarily dominate the runtime.

**Comment by asurve** [comment]
Addressed review comments.

**Comment by mboehm7** [comment]
LGTM; @lresende please merge

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
