### PR TITLE
[SYSML-282] Recompile improvements in update thread id

### PR DESCRIPTION
**Pull request by asurve**

### CODE REVIEW

**Comment by shirisht** [comment]
Arvind, If the change is particularly relevant to parfor, please indicate so either in the title or description. Thank you.

**Comment by asurve** [comment]
Shires, Change is generic and being called from parlor, and recompiler  as well. -Arvind

**Comment by mboehm7** [comment]
ok, just two style comments: (1) please make the constant 'private static final int', and (2) the search for the n-th occurence of a character exists in StringUtils - you might want to use that to make it more readable. Thanks.

**Comment by asurve** [comment]
Review comments addressed.

**Comment by asurve** [comment]
Addressed review comments.

**Comment by mboehm7** [comment]
one more thing: the second call to ordinalIndexOf scans the entire string again - please use indexOf(iPos+1) there.

**Comment by mboehm7** [comment]
LGTM

**Comment by asurve** [comment]
Please accept this pull request.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
