### PR TITLE
[SYSML-312] Refactor unit tests

### PR DESCRIPTION
**Pull request by gweidner**
This PR continues the pattern of previous PRs to refactor additional packages under functions including:
data, indexing, parfor, quaternary, recompile, ternary, transform.  Also updated matrix_full_other and matrix_full_cellwise to incorporate previous feedback (e.g., used base class methods for input, output, expected directories).  The matrix_full_other changes also include removing cached files to reduce disk space.  Also updated 2 package suites to include additional unit tests.

### CODE REVIEW

**Comment by gweidner** [comment]
All 4149 tests have passed in pr build 105.  I've made 1 additional commit for pom.xml to switch back to running functions.aggregate unit tests as package suite until new tests refactored.

**Comment by gweidner** [comment]
Also verified on local test environment that test data no longer generated in src tree for the packages included in the change set.  

@shirisht, @frreiss - Although the PR includes a large number of files, the modifications are similar to those approved in other related PRs and is ready for review.

@lresende Please Merge before freezing git repository and switching to apache.

**Comment by lresende** [comment]
PR Merged

**Comment by frreiss** [comment]
LGTM. I like that our test code is now 250 lines shorter :)

**Pull request closed without merging**
