### PR TITLE
[SYSML-319] Reuse R-script expected results in matrix_full_other tests

### PR DESCRIPTION
**Pull request by gweidner**
This change set continues the work done in SYSML-313 and modifies unit tests in test.integration.functions.binary.matrix_full_other plus base test class to optionally reusing R-script expected data.  This reduced the time to run the matrix_full_other unit tests by 30%.  Additional details and results available in R script section of updated design document in SYSML-286.

### CODE REVIEW

**Comment by gweidner** [comment]
All unit tests passed for PR build 54.

**Comment by frreiss** [comment]
LGTM overall. I see a lot of string concatenations involving the variable EXPECTED_DIR; I recommend making separate functions to compute the major paths (input, output, expected, etc.) for the current test case, in case we need to change the directory structure again in the future.

**Comment by gweidner** [comment]
I've created separate JIRA [SYSML-343] (https://stc-jira.svl.ibm.com:8443/browse/SYSML-343) for improving the directory naming processing.  With LGTM from previous comment,  @lresende please merge.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
