### PR TITLE
Generate Matrix with random values through local memory

### PR DESCRIPTION
**Pull request by asurve**
Generate Matrix with random values through local memory if there is sufficient memory.

### CODE REVIEW

**Comment by shirisht** [comment]
Arvind, we already have a CP version of Rand instruction, isn't it? 
Is the intention of this change to provide a "recompilation hook" for rand() for handling the case of unknown dimensions at the time of generating instructions (during compile or recompile) ?

**Comment by mboehm7** [comment]
yes, the goal is to add a "recompilation hook" for rand , the use case is rand(rows=sum(X)) in decision tree.

**Comment by asurve** [comment]
Addressed review comments.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
