### PR TITLE
[SYSML-315] [Test] Remove 'CleanUpTest' From WhileTest

### PR DESCRIPTION
**Pull request by dusenberrymw**
Removing 'CleanUpTest' test from WhileTest as it interferes with other tests running in parallel by attempting to delete all temporary folders, and is not needed.

### CODE REVIEW

**Comment by mboehm7** [comment]
Thanks for bringing up this issue. There are two orthogonal problems: (1) this call to checkForTemporaryFiles does not actually check the scratch_space (what it is supposed to do) - it would be good to fix and rename this generic method in testutils, (2) wrt to isolated parallel test execution, I would recommend to only check for the process-local temporary directory, i.e., something like that
String suffix = File.separator+Lop.PROCESS_PREFIX+DMLScript.getUUID();
String pLocalDir = config.getTextValue(DMLConfig.SCRATCH_SPACE) + suffix;

If this does not work out, I'm fine with removing the test - however, unless there is a good reason, I'd like to have a test that checks for proper cleanup.

**Comment by dusenberrymw** [comment]
Alright, I've added the cleanup test back into this test suite, and altered it so that it only checks for this process's temporary directory, and so that it does not delete other temporary directories.  

While this is fine, I would say that we should be cautious in going down the route of testing if our tests are correct.

**Comment by dusenberrymw** [comment]
Test this, Jenkins.

**Comment by dusenberrymw** [comment]
Test this Jenkins.

**Comment by dusenberrymw** [comment]
Test this Jenkins

**Comment by mboehm7** [comment]
LGTM - thanks for modifying the test.

**Comment by dusenberrymw** [comment]
Great, no problem.

**Comment by dusenberrymw** [comment]
@lresende Can you merge this, please?

**Comment by lresende** [comment]
PR Merged

**Comment by dusenberrymw** [comment]
Great, thanks!

**Pull request closed without merging**
