### PR TITLE
[SYSML-329] Add link to documentation site to README

### PR DESCRIPTION
**Pull request by deroneriksson**
Added link to SystemML documentation site from main README. Additionally made update to R test instructions.

### CODE REVIEW

**Comment by mboehm7** [comment]
thanks Deron, LGTM - @lresende please merge;

@deroneriksson the two test issues can be ignored - both are caused by random seeds; for the indexing test, the error is in E-14 which can happen with random seeds; for the ctable error it's again due to a random seed - in this particular case a slight difference of ctable semantics shows up (because not all values are represented in the input) - we should increase the number of rows here to make this case more unlikely to happen. Alternatively, we could also fix the seed; but I like to have some tests with varying data in order to detect issues that only show up for specific value combinations (as we encountered in the past).

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by niketanpansare** [comment]
Thanks @deroneriksson for adding the link. The documentation site is very user-friendly :)

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
