### PR TITLE
[SYSML-351] Enable unit tests in functions.append to run in parallel

### PR DESCRIPTION
**Pull request by gweidner**
This applies the same pattern of changes made in SYSML-313 to package com.ibm.bi.dml.test.integration.functions.append as described in document attached to SYSML-286.  The package functions.append contains two relatively long tests (AppendMatrix and AppendChain).  When run as a suite, the set takes ~25 minutes but when run in parallel ~15 minutes as mentioned in the 'Addtional Packages' section of the document.  Note the pom.xml change to disable the corresponding Suite class will be handled in a separate PR to help minimize merge conflicts as a few other PRs to be submitted to migrate other long-running packages.

### CODE REVIEW

**Comment by gweidner** [comment]
No test failures shown in 3,871 unit tests passed as reported for this PR at http://169.54.146.42:8080/job/SystemML-PullRequestBuilder/66/testReport/.  It appears that 194 of expected 4065 tests were not run in application.dml (-97) and applications.pydml (-97) which are unrelated to the changes in this PR.

**Comment by gweidner** [comment]
A similar situation (3871 tests instead of 4065) happened in http://169.54.146.42:8080/job/SystemML-PullRequestBuilder/57/testReport/.

**Comment by gweidner** [comment]
Test this Jenkins.

**Comment by gweidner** [comment]
Jenkins retest.

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by gweidner** [comment]
Incorporated code review comments from similar PR for SYSML-362:
Removed TARGET_ variables and replaced with references to base class input/output/expected directory methods.
Moved/Merged loadTestConfiguration before accessing directory methods to ensure baseDirectory initialized.

**Comment by shirisht** [comment]
The changes are fine but let us wait for other PRs to be merged, so that the relevant change to pom.xml is combined with rest of the changes here.

**Comment by shirisht** [comment]
LGTM 
@lresende Please merge.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
