### PR TITLE
Fix Constant Folding

### PR DESCRIPTION
**Pull request by asurve**
In ConstantFolding some foldings were skipped due to
   -- Predicates could not be evaluated though one of the predicate was false in conjunctive case or was true in disconjunctive case.

### CODE REVIEW

**Comment by mboehm7** [comment]
again, this is a very good catch, but we need do some cleanups

1) please delete removeAllParentReferences - the loop deletes all but the last element and the subsequent clear deletes the last. You should directly call clear from the rewrite.
2) also, you might want to add a comment to 'replace operator' to clarify that the root->parent link cannot be deleted right away

**Comment by asurve** [comment]
Removed newly added function in HopRewriteUtils, as its not being used.

**Comment by mboehm7** [comment]
LGTM

**Comment by asurve** [comment]
Please do pull request on this one.

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by asurve** [comment]
This PR was built successfully originally when changes were put in.
Recently, its failing with no error. 
With latest built, its status color is GRAY. 
Can someone look into JenKins side?

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
